### PR TITLE
Backport #2

### PR DESCRIPTION
**Pull request by carlopi**
Copy of https://github.com/lmangani/duckdb-extension-clickhouse-sql/pull/2.

There were some issue with the actions used underneath, that should now be fixed via https://github.com/duckdb/extension-ci-tools/pull/46.

Thanks for the patience, I suppose this should now work (as it should also close and reopen the previous PR).
Tested on a fork at https://github.com/carlopi/duckdb-extension-clickhouse-sql/actions/runs/9853610199/job/27204552083

### CODE REVIEW

**Comment by carlopi** [comment]
Either this or #2 will fix #1.

@lmangani, thanks for iterating on this, we uncovered a couple of problems in our setup.

**Comment by lmangani** [comment]
I can't understand - Since actions succeed I guess we can merge this PR and deal with the results directly in the main branch

**Comment by carlopi** [comment]
Magic of GitHub, I think this is good to merge, I think the other failures where connected at the original commit, since GitHub can't see there is some hidden state where now the proper action is run.

Thanks for bearing with this / experimenting on this.

**Comment by lmangani** [comment]
I really appreciate the help @carlopi! Next I need to learn how to submit this to the community repo!
Is there an action to support that workflow or it just needs a pointer? In which case... also need to learn where builds need to be

**Pull request merged**
