### PR TITLE
Migrate to DuckDB 1.1.0

### PR DESCRIPTION
**Pull request by lmangani**
Adding default parameters to scalar macros defined as a DefaultMacro

- https://github.com/duckdb/duckdb/pull/13494

### CODE REVIEW

**Comment by lmangani** [comment]
@carlopi might need some help with this 🙏 grazie in anticipo

**Comment by carlopi** [comment]
Hi, I think to actually test this you would also need, as part of this PR, to change `.github/workflows/MainDistributionPipeline.yml` so that the core part looks like:
```
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      extension_name: chsql

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@main
    secrets: inherit
    with:
      duckdb_version: main
      extension_name: chsql
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
```
(note `main` instead of `v1.0.0`)
Alternatively you can set on a specific commit (say latest nigthly build, `1e883cd4d87d812166d035e180145a85c608ad6f`)

**Comment by lmangani** [comment]
@carlopi i'm totally lost in API changes, currently broken builds due to .hpp mismatches

**Comment by carlopi** [comment]
I can also take over later, I guess this and the original one from @Alex-Monahan will need the same fixes (so maybe Alex will get to do them??)

**Comment by Alex-Monahan** [comment]
Hi folks! I was able to make a PR for the scalar macro default changes and it was merged on DuckDB's main branch. Does that help here at all, or is there more that needs to be done?

https://github.com/duckdb/duckdb/pull/13494

**Comment by lmangani** [comment]
> Hi folks! I was able to make a PR for the scalar macro default changes and it was merged on DuckDB's main branch. Does that help here at all, or is there more that needs to be done?
> 
> [duckdb/duckdb#13494](https://github.com/duckdb/duckdb/pull/13494)

Hey @Alex-Monahan well I tried to follow the PR and failed so far - certainly my fault porting from your example I assume but still trying to understand, very possibly just related to the wrong headers being included...

**Comment by Alex-Monahan** [comment]
Hi Lorenzo!

Since DuckDB 1.1 launches next week, I think that it is probably best to wait for that and retest. Once you upgrade to 1.1, there shouldn't be any cpp or hpp files to include a copy of in your extension - they will all be in the duckdb git submodule. 

I tested this with my own extension and upgrading the duckdb submodule to the main branch (and doing a git pull) instead of 1.0.0 was enough to get things going for me!

If you wouldn't mind, could you retest with 1.1.0 and then let me know if you encounter any issues?

Thanks!
-Alex

**Comment by lmangani** [comment]
Thank you so much @Alex-Monahan and @carlopi we're back on track with 1.1.0 🎉

**Pull request merged**
